// ===== generated by DUGS from project 'b' =====
// Edit the graph in DUGS and re-export; changes here get overwritten.

#include <Servo.h>

Servo servo_9;
int pick = 0;

void setup() {
  servo_9.attach(9);
  servo_9.write(0);
  randomSeed(analogRead(A0));
}

void loop() {
  // --- On Repeat 6 ---
  // --- Servo 2 ---
  servo_9.write(90);
  // --- Wait 12 ---
  delay(1000);
  // --- Servo 8 ---
  servo_9.write(0);
  // --- Wait 13 ---
  delay(5000);
  // --- Random 15 ---
  pick = random(0, 3 + 1);
}
